/**
 * MMOS News Production - Text Generate Capability Stub
 */

import type { DraftResult, HeadlineResult, VerificationResult } from '../types.js';

export interface TextGenerateInput {
  type: 'article' | 'summary';
  headline: HeadlineResult;
  verification: VerificationResult;
  targetLength?: number;
}

export interface TextGenerateCapability {
  generate(input: TextGenerateInput): Promise<DraftResult | string>;
}

export function createTextGenerateCapability(): TextGenerateCapability {
  return {
    async generate(input: TextGenerateInput): Promise<DraftResult | string> {
      console.log(`[TextGenerateCapability] Generating ${input.type}`);
      
      if (input.type === 'summary') {
        return generateSummary(input.verification);
      }
      
      return generateArticle(input.headline, input.verification);
    },
  };
}

function generateArticle(headline: HeadlineResult, verification: VerificationResult): DraftResult {
  const verifiedFactsText = verification.verifiedFacts
    .map(f => `- ${f.statement} (Source: ${f.source})`)
    .join('\n');
  
  const content = `# ${headline.headline}

${headline.subheadlines.map(sh => `**${sh}**`).join('\n\n')}

## Key Facts

${verifiedFactsText}

## Full Report

Following the announcement, government officials revealed comprehensive details about the initiative, including implementation timeline, budget allocation, and expected impact on the community.

### Implementation Details

The program will be rolled out in three phases over the next 18 months, with initial focus on infrastructure development and technology deployment.

### Economic Impact

Analysts predict significant economic benefits, with projections showing potential growth in the affected sectors and job creation across multiple industries.

### Next Steps

Authorities will continue monitoring the progress and provide regular updates to the public regarding milestone achievements.

---

*This news article was generated by MMOS AI News Production System.*`;
  
  return {
    content,
    wordCount: content.split(/\s+/).length,
    sections: ['Introduction', 'Key Facts', 'Full Report', 'Implementation Details', 'Economic Impact', 'Next Steps'],
  };
}

function generateSummary(verification: VerificationResult): string {
  const keyPoints = verification.verifiedFacts.slice(0, 3).map(f => f.statement);
  return `## Summary

${keyPoints.map((point, i) => `${i + 1}. ${point}`).join('\n')}

**Verification Status:** ${verification.confidenceScore}% verified
**Verified Facts:** ${verification.verifiedFacts.length}
**Unverified Claims:** ${verification.unverifiedClaims.length}`;
}